### ISSUE TITLE
Register the ontology on LOV

### ISSUE THREAD

**Issue by clange** [WDAqua/QAOntology#4]
… once it's been published (see #3) and has a persistent URI (#2). See http://lov.okfn.org.

**Comment by D063520** [comment]
Mhmmm .... this is strange .... LOV is returning an error:

An error occurred:
org.apache.jena.riot.RiotException: Failed to determine the triples content type: (URI=file:///usr/local/lov/lovnode/https://w3id.org/wdaqua/qanary : stream=text/plain : hint=null) at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:755) at org.apache.jena.riot.RDFDataMgr.parse(RDFDataMgr.java:652) at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:211) at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:104) at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:95) at org.apache.jena.riot.RDFDataMgr.loadModel(RDFDataMgr.java:331) at org.lov.LovBotVocabAnalyser.analyse(LovBotVocabAnalyser.java:58) at org.lov.LovBotVocabAnalyser.analyseVocabURI(LovBotVocabAnalyser.java:48) at org.lov.cli.Suggest.exec(Suggest.java:71) at arq.cmdline.CmdMain.mainMethod(CmdMain.java:101) at arq.cmdline.CmdMain.mainRun(CmdMain.java:63) at arq.cmdline.CmdMain.mainRun(CmdMain.java:50) at org.lov.cli.Suggest.main(Suggest.java:27)

So it seams like it is accessing "https://w3id.org/wdaqua/qanary " where there is an HTML page. But:

curl -H "Accept: text/turtle" https://w3id.org/wdaqua/qanary# 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>303 See Other</title>
</head><body>

<h1>See Other</h1>

<p>The answer to your request is located <a href="https://raw.githubusercontent.com/WDAqua/QAOntology/master/qanary.ttl">here</a>.</p>

<hr>

<address>Apache/2.4.7 (Ubuntu) Server at w3id.org Port 443</address>
</body></html>

Is giving back the right thing. So seams like is not doing content negociation. Shoud I give him the GitHub Address directly?

**Comment by D063520** [comment]
Strange because the W3C validation service does not complain:

https://www.w3.org/RDF/Validator/rdfval?URI=https%3A%2F%2Fw3id.org%2Fwdaqua%2Fqanary%23&PARSE=Parse+URI%3A+&TRIPLES_AND_GRAPH=PRINT_TRIPLES&FORMAT=PNG_EMBED

**Comment by clange** [comment]
I could imagine that the W3C validator only cares about the content that's returned not about the headers, whereas LOV is a bit more pedantic. The problem is that publishing at GitHub does not really work, because one has no influence on the HTTP headers. You can see the problem by running

```
wget -O /dev/null -S --header 'Accept: application/rdf+xml' https://w3id.org/wdaqua/qanary
```

You will see that the content type that's returned is `text/plain`, whereas a LOD client would expect `application/rdf+xml`.

I see two possibilities:
1. @kulsingh can you please get in touch with those EIS colleagues (like Irlán) who have published vocabularies before, on vocab.cs.uni-bonn.de? I actually see that one of the existing vocabularies, http://vocab.cs.uni-bonn.de/eis/rami/, is not published in a conforming way either, but I think they know what should be done in principle.
2. publish the vocabulary as a static file in someone's webspace, e.g. `~/public_html` on the computer science @ Uni Bonn servers. Then, an .htaccess file not too different from the one for w3id will be needed; see https://www.w3.org/TR/swbp-vocab-pub/ for how it works.
